# Site settings
title: Double Offshore
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "/doubleoffshore" # the subpath of your site, e.g. /blog/
url: "http://pudo.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
