import os

DEBUG = bool(os.environ.get('DEBUG'))
ASSETS_DEBUG = DEBUG

FREEZER_DESTINATION = '../build'
FREEZER_REMOVE_EXTRA_FILES = True

DOC_ID = '1gCJg7qE1GPPWvgS4rYZzuc7G5DvsfhDI2tRCtxvF10k'
RIGS_SHEET = '0'
COMPANIES_SHEET = '1295203706'

if 'MEMCACHIER_SERVERS' in os.environ:
    CACHE_TYPE = 'memcached'
    CACHE_MEMCACHED_SERVERS = [os.environ.get('MEMCACHIER_SERVERS')]
    CACHE_MEMCACHED_USERNAME = os.environ.get('MEMCACHIER_USERNAME')
    CACHE_MEMCACHED_PASSWORS = os.environ.get('MEMCACHIER_PASSWORD')
else:
    CACHE_TYPE = 'simple'
